language: python
python:
  - "2.7"
sudo: false
virtualenv:
  system_site_packages: true
before_script:
  - "export DISPLAY=:99.0"
  - "export AUDIODEV=null" # PyGame needs audio device
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
addons:
  apt:
    packages:
    - python-pygame
    - python-yaml
    - python-qt4
    - python-scipy
    - python-pyglet
before_install:
  - pip install pillow webcolors python-datamatrix python-qdatamatrix python-pseudorandom openpyxl qtpy expyriment psychopy==1.85.04 json_tricks configobj
  - wget https://github.com/smathot/python-yamldoc/archive/release/0.2.0.tar.gz -O yamldoc.tar.gz
  - tar -xzvf yamldoc.tar.gz
  - export PYTHONPATH=$PYTHONPATH:python-yamldoc-release-0.2.0
script: ./run_unittests.py
